### ISSUE TITLE
Move climsoft-api branch to main repo and update requirements.txt

### ISSUE THREAD

**Issue by isedwards** [opencdms/opencdms-server#48]
Move: https://github.com/faysal-ishtiaq/climsoft-api.git@data-forms
to: https://github.com/opencdms/climsoft-api.git@main

and update requirements.txt

**Comment by faysal-ishtiaq** [comment]
@isedwards this task [ https://github.com/faysal-ishtiaq/climsoft-api.git@data-forms ] is still in progress. And some minor updates such as `/search` endpoint modification, is done on this branch, in that case, should I merge whatever is done in `data-forms` branch and then replace the repo URL? Or should I complete the in-progress tasks in `data-forms` branch and then merge?

**Comment by isedwards** [comment]
Happy for it to be merged now (since we're already using that branch online)

**Comment by faysal-ishtiaq** [comment]
@isedwards resolved with this commit https://github.com/opencdms/opencdms-api/commit/2954438885e9ba6a1a6147d2543e621bbc6c2164
